//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        public int ID { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
        public string CMND { get; set; }
        public Nullable<int> LoaiDG { get; set; }
        public Nullable<System.DateTime> NgayLapThe { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<int> SoSachMuon { get; set; }
        public string TinhTrangThe { get; set; }
        public Nullable<bool> Xoa { get; set; }
    }
}
