//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuTra
    {
        public int ID { get; set; }
        public Nullable<int> ID_PhieuMuon { get; set; }
        public Nullable<int> ID_DocGIa { get; set; }
        public Nullable<int> SoSachTra { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
    }
}
