//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThuVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuon
    {
        public int ID { get; set; }
        public Nullable<int> ID_DG { get; set; }
        public Nullable<int> TongSoSachMuon { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public string TinhTrang { get; set; }
    }
}
